#!/usr/bin/env bash
# from github.com/ThePrimeagen/.dotfiles

if [[ $# -eq 1 ]]; then
    selected=$1
else
    workDirs=$(fdfind '.git$' -H -t d ~/work --min-depth 1 --exec dirname {})
    otherDirs=$(fdfind . ~/Documents/ ~/projects ~/ --min-depth 1 --max-depth 1 -t d -H)
    selected=$(echo "$otherDirs"$'\n'"$workDirs" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
selected_name=$(echo "$selected" | sed -e "s#$HOME/##" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
